# TODO: replace by ruff & mypy soon
name: "Pylint"

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'test_pylint'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install dependencies and show pylint deps
        run: |
          # 步骤 1: 安装项目依赖 (确保 pylint 在这里)
          uv sync --extra all --extra dev
      
          # 步骤 2: 确保安装 pipdeptree
          # 这一行很可能是您遗漏的，或者放错了位置
          echo "Installing pipdeptree..."
          uv pip install pipdeptree
      
          # 步骤 3: 现在系统已经认识 pipdeptree 命令了，可以安全调用
          echo "Pylint dependency tree:"
          pipdeptree -p pylint

      - name: Check DGL version
        run: |
          uv run python -c "import dgl; print(dgl.__version__)"

      - name: Analysing the code with pylint
        run: |
          uv run bash ./style/code_format_and_analysis.sh -p
